import math
from random import Random
import numpy as np

class RNG(object):
    
    """
    Class RNG contains two random number streams, one for IAT and one for ST.

    Both RNS can be set during initialization or separately. The next random numbers are generated by the functions
    get_iat() or get_st().
    """
    
    def __init__(self, rns1, rns2):
        """
        Initialize a RNG object with two RNS given.
        :param rns1: represents the RNS for the inter-arrival times.
        :param rns2: represents the RNS for the service times.
        """
        self.iat_rns = rns1
        self.st_rns = rns2
    
    def set_iat_rns(self, rns1):
        """
        Set a new RNS for the inter-arrival times.
        """
        self.iat_rns = rns1
        
    def set_st_rns(self, rns2):
        """
        Set a new RNS for the service times.
        """
        self.st_rns = rns2
        
    def get_iat(self):
        """
        Return a new sample of the IAT RNS
        """
        return self.iat_rns.next()
    
    def get_st(self):
        """
        Return a new sample of the ST RNS
        """
        return self.st_rns.next()


class RNS(object):
    
    """
    Basic abstract class for random number streams.

    To be implemented in subclass.
    Contains a Random class r in order to allow different seeds for different RNS
    """

    def __init__(self, the_seed=None):
        """
        Initialize the general RNS with an optional seed.
        All further initialization is done in subclass.
        """
        self.r = Random(the_seed)

    def set_parameters(self, *args):
        NotImplementedError("Implement in subclass")

    def next(self):
        """
        Method should be overwritten in subclass.
        """
        return 0
    

class ExponentialRNS(RNS):
    
    """
    Class to provide exponentially distributed random numbers. After initialization, new numbers can be generated
    using next(). Initialization with given parameters and optional seed.
    :param the_seed: optional seed for the random number stream
    """
    
    def __init__(self, lambda_, the_seed=None):
        """
        Initialize Exponential RNS and set the parameters.
        """
        super(ExponentialRNS, self).__init__(the_seed)
        # TODO Task 3.1.1: Your code goes here
        """
        Also modify the list of input parameters according to the needs of this distribution.
        """
        self.lambda_ = -1
        self.set_parameters(lambda_)
        #pass
        
    def set_parameters(self, params):
        """
        Set parameters of the distribution.
        """
        # TODO Task 3.1.1: Your code goes here
        """
        Also modify the list of input parameters according to the needs of this distribution.
        """
        self.lambda_ = params
        #pass
        
    def next(self):
        """
        Generate the next random number using the inverse transform method.
        """
        # TODO Task 3.1.1: Your code goes here
        return -math.log(1-self.r.random()) / float(self.lambda_)
        #pass
        

class UniformRNS(RNS):
    
    """
    Class to provide exponentially distributed random numbers. After initialization, new numbers can be generated
    using next(). Initialization with given parameters and optional seed.
    :param the_seed: optional seed for the random number stream
    """
    
    def __init__(self, a, b, the_seed=None):
        """
        Initialize Uniform RNS and set the parameters.
        """
        super(UniformRNS, self).__init__(the_seed)
        # TODO Task 3.1.1: Your code goes here
        """
        Also modify the list of input parameters according to the needs of this distribution.
        """
        self.a = -1
        self.b = -1
        self.set_parameters(a,b)
        #pass
        
    def set_parameters(self, a,b):
        """
        Set parameters.
        """
        # TODO Task 3.1.1: Your code goes here
        """
        Also modify the list of input parameters according to the needs of this distribution.
        """
        self.a = a
        self.b = b
        #pass
        
    def next(self):
        """
        Generate the next random number using the inverse transform method.
        """
        # TODO Task 3.1.1: Your code goes here

        return self.a + (self.b - self.a)*self.r.random()
        #pass